# Generated by Django 4.2.6 on 2023-11-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_team_creator_alter_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(to='tasks.achievement'),
        ),
    ]
