# Generated by Django 4.2.6 on 2023-11-07 21:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_alter_team_description_alter_team_name"),
        ("tasks", "0004_team_description_team_members_alter_team_name"),
    ]

    operations = []
