# Generated by Django 4.2.6 on 2023-11-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='received_invites',
            field=models.ManyToManyField(blank=True, related_name='received_invites', to='tasks.invite'),
        ),
        migrations.AddField(
            model_name='user',
            name='sent_invites',
            field=models.ManyToManyField(blank=True, related_name='sent_invites', to='tasks.invite'),
        ),
        migrations.AlterField(
            model_name='user',
            name='achievements',
            field=models.ManyToManyField(blank=True, to='tasks.achievement'),
        ),
    ]
