# Generated by Django 4.2.6 on 2023-12-01 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_achievement_user_received_invites_user_sent_invites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
