# Generated by Django 4.2.6 on 2023-11-27 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_alter_task_team'),
        ('tasks', '0007_user_received_invites_user_sent_invites_and_more'),
    ]

    operations = [
    ]
