# Generated by Django 4.2.6 on 2023-12-01 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_team_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='creator',
        ),
    ]
