# Generated by Django 4.2.6 on 2023-12-09 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_alter_team_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assignedUsername',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
