# Generated by Django 4.2.6 on 2023-12-09 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_assignedusername'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
