# Generated by Django 4.2.6 on 2023-12-11 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='finished_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
