# Generated by Django 4.2.6 on 2023-12-11 19:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_remove_task_assigned_users_task_assigned_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_user',
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_users',
            field=models.ManyToManyField(related_name='tasks_assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
