# Generated by Django 4.2.6 on 2023-12-12 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_user_is_staff_alter_user_is_superuser'),
        ('tasks', '0021_remove_task_assigned_user_task_assigned_users'),
    ]

    operations = [
    ]
